toysmarket/apps/accounts/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from django.contrib.auth.forms import AdminPasswordChangeForm
from toysmarket.apps.accounts.views import (CreateUserView, LoginUserView,
                                            AccountInfoView, Logout, UserEdit,
                                            ConfirmEmail)

from django.contrib.auth import views as auth_views


urlpatterns = patterns('',
                       url(r'^password/change/$', auth_views.password_change,
                           {'template_name': 'accounts/password_change.html', }, name='password_change'),
                       url(
                           r'^password/change/done/$',
                           auth_views.password_change_done,
                           {'template_name': 'accounts/password_change_done.html'},
                           name='password_change_done'),
                       url(
                           r'^password/reset/$',
                           auth_views.password_reset,
                           {'template_name': 'accounts/password_reset.html'},
                           name='password_reset'),
                       url(r'^password/reset/done/$',
                           auth_views.password_reset_done,
                           {'template_name': 'accounts/password_reset_done.html'},
                           name='password_reset_done'),
                       url(
                           r'^password/reset/complete/$',
                           auth_views.password_reset_complete,
                           {'template_name': 'accounts/password_reset_complete.html'},
                           name='password_reset_complete'),
                       url(r'^password/reset/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
                           auth_views.password_reset_confirm,
                           {'template_name': 'accounts/password_reset_confirm.html'},
                           name='password_reset_confirm'),
                       url(r'^registration/$', CreateUserView.as_view(), name='registration'),
                       url(r'^login/$', LoginUserView.as_view(), name='login'),
                       url(r'^logout/$', Logout.as_view(), name='logout'),
                       url(r'^edit/$', UserEdit.as_view(), name='user_edit'),
                       url(r'^confirm/(?P<key>[^/]+)/(?P<uid>[0-9]+)/$',
                           ConfirmEmail.as_view(), name='confirm_email'),
                       url(r'^user_address/$',
                           'accounts.views.user_address', name='user_address'),
                       url(r'^profile/$', AccountInfoView.as_view(),
                           name='profile')
)

toysmarket/apps/order/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from toysmarket.apps.order.views import BasketView


urlpatterns = patterns('order.api',
    url(r'^add/$', 'order_add', name='api_order_add'),
    url(r'^product_del/$', 'product_del', name='api_product_del'),
    url(r'^clean/$', 'order_remove', name='api_order_remove'),
    url(r'^approve/$', 'order_approve', name='api_order_approve'),
)

urlpatterns += patterns(
    '',
    url(r'^basket/$', BasketView.as_view(), name='basket'),
)

toysmarket/apps/product/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from toysmarket.apps.product.views import (IndexView, ProductListView,
                                           ProductDetailView, SearchListView)

urlpatterns = patterns('',
                       url(r'^$', IndexView.as_view(), name='index'),
                       url(r'^catalog/(?P<slug>([-\w]+)*)?$',
                           ProductListView.as_view(),
                           name='product_list'),
                       url(r'^goods/(?P<slug>[-\w]+)-(?P<good_id>\d+)/$',
                           ProductDetailView.as_view(),
                           name='product_details'),
                       url(r'^search/$', SearchListView.as_view(),
                           name='search'),
)

urls.py
from django.conf.urls import patterns, include, url

from toysmarket.apps.product.views import UploadCsvFile
from django.contrib import admin

from django.views.generic import TemplateView

from django.conf import settings

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^', include('toysmarket.apps.product.urls')),
    url(r'^upload_csv/', UploadCsvFile.as_view(), name='upload_csv'),
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^ckeditor/', include('ckeditor.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^error_message/',
        TemplateView.as_view(template_name="error_page.html"),
        name='error_message'),
    url(r'^accounts/', include('toysmarket.apps.accounts.urls')),
    url(r'^order/', include('toysmarket.apps.order.urls')),
    url(r'^pages/', include('django.contrib.flatpages.urls')),
    url(r'^robots.txt$',
        TemplateView.as_view(template_name="robots.txt"), name='robots.txt'),
)

if settings.DEBUG:
    urlpatterns += patterns(
        '',
        url(
            r'^media/(?P<path>.*)$',
            'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT}
        ),
    )

toysmarket/apps/accounts/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.utils.translation import ugettext as _

from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.db import models
from django.utils import timezone

from django.contrib.sites.models import Site

from imagekit.models import ProcessedImageField
from pilkit.processors.resize import ResizeToFill
from simple_email_confirmation import SimpleEmailConfirmationUserMixin

from celery import current_app



class MyUserManager(BaseUserManager):

    def create_user(self, email, password=None, **extra_fields):
        """
        Creates and saves a User with the given email and password.
        """
        now = timezone.now()
        email = MyUserManager.normalize_email(email)
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(email=email, is_staff=False, is_active=True, is_superuser=False,
                          last_login=now, created_at=now, **extra_fields)

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password, **extra_fields):
        u = self.create_user(email, password, **extra_fields)
        u.is_staff = True
        u.is_active = True
        u.is_superuser = True
        u.save(using=self._db)
        return u


class Address(models.Model):
    """
        Adress model
    """
    city = models.CharField(max_length=255, verbose_name=_('Город'))
    address = models.CharField(max_length=255, verbose_name=_('Адрес'),
                               blank=True, null=True)
    postcode = models.CharField(max_length=255, verbose_name=_('Индекс'),
                                blank=True, null=True)
    user = models.ForeignKey('User', verbose_name=_('Пользователь'),
                             related_name='adress')

    def __unicode__(self):
        return unicode(self.user)

    class Meta:
        verbose_name = _('Адрес')
        verbose_name_plural = _('Адреса')


class User(SimpleEmailConfirmationUserMixin, AbstractBaseUser, PermissionsMixin):
    GENDER = (
        (0, _('Не указан')),
        (1, _('Мужчина')),
        (2, _('Женщина')),
    )

    username = models.CharField(
        max_length=100, verbose_name=_('Имя пользователя'), blank=True, null=True)
    email = models.EmailField(unique=True, db_index=True,
                              verbose_name=('E-mail'))
    avatar = ProcessedImageField(upload_to='avatars',
                                 processors=[ResizeToFill(100, 50)],
                                 format='JPEG',
                                 options={'quality': 95},
                                 blank=True, null=True)
    phone = models.CharField(
        max_length=255, verbose_name=_('Телефон'), blank=True, null=True)
    ip_adress = models.CharField(max_length=255, verbose_name=_('IP-адрес'),
                                 blank=True, null=True)
    gender = models.IntegerField(choices=GENDER, default=0,
                                 verbose_name=_('Пол'))
    first_name = models.CharField(_('Имя'), max_length=30, blank=True)
    last_name = models.CharField(_('Фамилия'), max_length=30, blank=True)
    created_at = models.DateTimeField(_('Дата регистрации'), auto_now=True)

    is_active = models.BooleanField(default=True,
                                    verbose_name=_('Активный'))
    is_staff = models.BooleanField(default=False)

    objects = MyUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _('Пользователь')
        verbose_name_plural = _('Пользователи')

    def __unicode__(self):
        return unicode(self.email)

    def get_short_name(self):
        return self.first_name

    def get_full_name(self):
        """
            Returns the first_name plus the last_name, with a space in between.
        """
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def save(self, *args, **kwargs):
        update_model = bool(self.pk)
        super(User, self).save(*args, **kwargs)
        if not update_model:
            user_confirm = {
                'key': self.confirmation_key,
                'uid': self.id,
                'name': self.first_name,
                'last_name': self.last_name,
                'SITE_URL': Site.objects.get_current().domain
            }
            current_app.send_task(
                'emails.send_email',
                args=[
                    'registration',
                    self.email,
                    user_confirm,
                    u'777toys.com.ua - Регистрация на сайте'
                ],
            )

toysmarket/apps/core/models.py
from django.db import models

# Create your models here.

toysmarket/apps/order/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.utils.translation import ugettext as _

from django.conf import settings
from django.db.models.deletion import PROTECT

from django.db import models

from decimal import Decimal

from django.db.models.signals import post_save
from django.dispatch import receiver
from toysmarket.apps.product.models import Product


class Delivery(models.Model):
    """ Delivery """
    title = models.CharField(max_length=255, verbose_name=_('Заголовок'))

    class Meta:
        verbose_name = _("Способ доставки")
        verbose_name_plural = _("Способы доставки")

    def __unicode__(self):
        return unicode(self.title)


class Order(models.Model):
    """Model for user`s orders."""
    PAYED = 0
    PROCESS = 1

    CACHE = 0
    WITHOUT_CACHE = 1

    ORDER_STATUS = (
        (PAYED, _("Оплачен")),
        (PROCESS, _("В процессе"))
    )

    PAYMENT_TYPE = (
        (CACHE, _('Наличными')),
        (WITHOUT_CACHE, _('Безналичными'))
    )

    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             verbose_name=_('Покупатель'),
                             related_name='userorder',
                             on_delete=PROTECT)
    uid = models.CharField(max_length=50, unique=True)
    delivery_type = models.ForeignKey(Delivery,
                                      verbose_name=_('Способ доставки'))
    payment_type = models.PositiveSmallIntegerField(_('Способ оплаты'),
                                                    choices=PAYMENT_TYPE,
                                                    default=CACHE)
    created_date = models.DateTimeField(auto_now_add=True)
    status = models.PositiveSmallIntegerField(_('Статус'),
                                              choices=ORDER_STATUS,
                                              default=PROCESS)
    delivery_address = models.CharField(
        max_length=250, blank=True, null=True, verbose_name=u'Адресс доставки')
    comment = models.TextField(verbose_name=_('Комментарий к заказу'),
                               blank=True,
                               null=True)

    class Meta:
        verbose_name = _('Order')
        verbose_name_plural = _('Orders')

    def __unicode__(self):
        return u"Order:%s" % (self.uid)

    def get_order_price(self):
        return sum([item.get_item_price() for item in self.orderitem.all()])
    get_order_price.short_description = _('Цена заказа')

    def get_user_information(self):
        return '<a href="/admin/accounts/user/%s">%s %s</a>' % (
            self.user.id,
            self.user.first_name,
            self.user.last_name)
    get_user_information.short_description = _('Имя, Фамилия')
    get_user_information.allow_tags = True

    def get_user_phone(self):
        return "%s" % self.user.phone
    get_user_phone.short_description = _('Телефон')


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='orderitem',
                              verbose_name=_('Заказ'))
    product = models.ForeignKey(Product, verbose_name=_('Товар'))
    quantity = models.SmallIntegerField(_('Количество'))

    class Meta:
        verbose_name = _('OrderItem')
        verbose_name_plural = _('OrderItems')

    def __unicode__(self):
        return u'Заказа #%s Название товара: %s' % (self.order.uid, self.product.name)

    def get_item_price(self):
        return Decimal(self.product.price *
                       self.quantity).quantize(Decimal('.01'))

    @property
    def name(self):
        return self.product.name

    @property
    def sku(self):
        return self.product.sku

    @property
    def price(self):
        return self.product.price


@receiver(post_save, sender=Order, dispatch_uid="order_unique")
def approve_purchase(sender, instance, **kwargs):
    """
        Order changed status
    """
    if instance.status == Order.PAYED:
        for item in instance.orderitem.all():
            if not item.product.total_sold:
                item.product.total_sold = item.quantity
            else:
                item.product.total_sold += item.quantity
            if not item.product.total_sold < item.product.items_in_stock:
                item.product.allow_buy = False
            item.product.save()
            item.product.category.clean_cache()

toysmarket/apps/extra_settings/forms.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django import forms
from .models import HitToys, SaleToys, NewToys

from toysmarket.apps.product.models import Product


class SliderForm(forms.ModelForm):

    def clean_sku(self):
        if not Product.objects.filter(sku=self.cleaned_data['sku']):
            raise forms.ValidationError(
                u'Такого артыкуля не существует')
        return self.cleaned_data['sku']


class HitToysForm(SliderForm):
    def clean_sku(self):
        super(HitToysForm, self).clean_sku()
        if HitToys.objects.filter(sku__iexact=self.cleaned_data['sku']).exclude(id=self.instance.id):
            raise forms.ValidationError(
                u'Слайд с таким артыкулем уже существует'
            )
        return self.cleaned_data['sku']

    class Meta:
        model = HitToys


class SaleToysForm(SliderForm):
    def clean_sku(self):
        super(SaleToysForm, self).clean_sku()
        if SaleToys.objects.filter(sku__iexact=self.cleaned_data['sku']).exclude(id=self.instance.id):
            raise forms.ValidationError(
                u'Слайд с таким артыкулем уже существует'
            )
        return self.cleaned_data['sku']

    class Meta:
        model = SaleToys


class NewToysForm(SliderForm):
    def clean_sku(self):
        super(NewToysForm, self).clean_sku()
        if NewToys.objects.filter(sku__iexact=self.cleaned_data['sku']).exclude(id=self.instance.id):
            raise forms.ValidationError(
                u'Слайд с таким артыкулем уже существует'
            )
        return self.cleaned_data['sku']

    class Meta:
        model = NewToys

toysmarket/apps/product/forms.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django import forms
from .models import CsvFile


class CsvFileForm(forms.ModelForm):

    class Meta:
        model = CsvFile

toysmarket/apps/core/views.py
from django.shortcuts import render

# Create your views here.

toysmarket/apps/extra_settings/views.py
from django.shortcuts import render

# Create your views here.

toysmarket/apps/order/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render

from django.views.generic import TemplateView

from toysmarket.apps.order.core.storage import RedisOrderStorage
from toysmarket.apps.order.models import Delivery, Order
# Create your views here.


class BasketView(TemplateView):
    """
    Basket Page
        template: basket.html
    """
    template_name = 'basket.html'

    def get_context_data(self, **kwargs):
        context = super(BasketView, self).get_context_data(**kwargs)
        order = RedisOrderStorage(self.request).get_from_storage()
        if order:
            context['product_list'] = []
            for item in order.order_items:
                product = item.product
                product.count = item.quantity
                product.sum = item.quantity * product.price
                context['product_list'].append(product)
        context['delivery_list'] = Delivery.objects.all()
        context['payment_list'] = Order.PAYMENT_TYPE
        return context

toysmarket/templates/accounts/login.html
{% extends 'base.html' %}
{% block extra_head %}
{% endblock %}
{% block title %} Интернет-магазин 777toys.com.ua: Вход в систему {% endblock %}
{% block content %}
<div class="welcome">Авторизация</div>
<form action="" method="post" id="login">
    {% csrf_token %}
    {% for field in form %}
    <fieldset>
        {% if field.errors %}
            <div class="control-group error">
                {{ field }}
                <span class="help-inline"> {{ field.errors.0 }}</span>
            <div>
        {% else %}
            {{ field }}
        {% endif %}
    </fieldset>
    {% endfor %}
    {% if form.non_field_errors %}
        <div class="control-group error">
            {{ form.non_field_errors }}
        <div>
    {% endif %}
    <input class="button filter-button" type="submit" value="Войти в магазин" />

    <br>
    <br>
    <a href="{% url 'registration'%}">Регистрация</a> <a href="{% url 'password_reset'%}">Восстановить пароль</a>
</form>
{% endblock %}

toysmarket/templates/accounts/password_change.html
{% extends 'base.html' %}

{% load i18n %}

{% block content %}
    <div class="welcome">Изменение пароля</div>
    <form method="post" action="" class="uniForm">
        {% csrf_token %}
        <input class="simple-input" placeholder="Старый пароль" id="id_old_password" name="old_password" type="password">
        <input class="simple-input" placeholder="Новый пароль" id="id_new_password1" name="new_password1" type="password">
        <input class="simple-input" placeholder="Подтверждение нового пароля" id="id_new_password2" name="new_password2" type="password">
        <input class="button filter-button" type="submit" value="Изменить" />
    </form>
    <script type="text/javascript">document.getElementById("id_old_password").focus();</script>
{% endblock %}

toysmarket/templates/accounts/password_change_done.html
{% extends 'base.html' %}

{% load i18n %}

{% block content %}
    <center><h3>Пароль изменён успешно.</h3></center>
{% endblock %}

toysmarket/templates/accounts/password_reset.html
{% extends "base.html" %}

{% block title %}Восстановление пароля{% endblock %}

{% block content %}
    <form method="post" action="">
        {% csrf_token %}
        <div class="register_wrapper">
            <div class="welcome">Восстановление доступа к аккаунту</div>
            <div id="loginmain_forms_re" class="register_main_wrap" style="padding-top: 1px">
                <div class="regmain_inputs" style="margin-top: 10px">
                    <p class="regmain_extratitle">Введите E-Mail под которым вы регистрировались</p>
                    <br>
                    <input class="simple-input" id="id_email" maxlength="254" name="email" type="email">
                    {% if form.email.errors %}
                        <div class="form_errors" style="margin-top: 14px">
                            <ul>
                                <li>{{ form.email.errors.0 }}</li>
                            </ul>
                        </div>
                    {% endif %}
                </div>
            </div>
            <input class="button filter-button" type="submit" value="Продолжить" />
        </div>
    </form>

    <script type="text/javascript">document.getElementById("id_email").focus();</script>
{% endblock %}

toysmarket/templates/accounts/password_reset_complete.html
{% extends "base.html" %}

{% block title %}Восстановление пароля{% endblock %}

{% block content %}
    <div class="register_wrapper">
        <div class="welcome">Восстановление доступа к аккаунту</div>
        <div id="loginmain_forms_re" class="register_main_wrap">
            <p class="regmain_extratitle_final">
                Пароль изменён успешно. Теперь вы можете <a href="{% url 'login' %}">войти</a>.
            </p>
        </div>
    </div>
{% endblock %}

toysmarket/templates/accounts/user_view.html
{% extends 'base.html' %}
{% load user_address %}
{% block content %}
<section role="main" class="main-section cabinet-section right">
    <!--tabs-->
    <div class="tabs-section tabs-section-js cabinet-bl">
        <ul class="tabs tabs-js clearfix">
            <li class="tab tab-current first-tab"><div class="tab-bl">Мои настойки</div></li>
            <li class="tab second-tab"><div class="tab-bl">Корзина</div></li>
            <li class="tab third-tab"><div class="tab-bl">Мои заказы</div></li>
        </ul>
        <div class="tab-content tab-content-js tab-content-visible">
            <table class="cabinet-info-tb">
                <tr>
                    <td class="cabinet-first-cell">Ваше имя:</td>
                    <td class="cabinet-second-cell">{{ user.last_name }} {{ user.first_name }}</td>
                </tr>
                <tr>
                    <td class="cabinet-first-cell">E-mail:</td>
                    <td class="cabinet-second-cell">{{ user.email }}</td>
                </tr>
                {% if user.phone %}
                <tr>
                    <td class="cabinet-first-cell">Телефон:</td>
                    <td class="cabinet-second-cell">+38 {{ user.phone }}</td>
                </tr>
                {% endif %}
                {% if address %}
                <tr>
                    <td class="cabinet-first-cell">Адреса для доставок:</td>
                    <td class="cabinet-second-cell">{{ address.city }}</td>
                </tr>
                {% endif %}
            </table>
            <div class="tar cabinet-info-footer">
                <p>
                    <a href="{% url 'user_edit' %}" class="goods-button button">Редактировать данные</a>
                </p>
                <p>
                    <a href="{% url 'password_change' %}" class="cabinet-link">Изменть пароль</a>
                </p>
            </div>
        </div>
        <div class="tab-content tab-content-js">
            <div class="tablebox basket-header">
                <div class="cellbox basket-tb-cell-num">№</div>
                <div class="cellbox basket-tb-cell-goods">Товар</div>
                <div class="cellbox basket-tb-cell-amt">Количество</div>
                <div class="cellbox basket-tb-cell-price">Цена</div>
                <div class="cellbox basket-tb-cell-sum">Сумма</div>
                <div class="cellbox basket-tb-cell-delete">Удалить</div>
            </div>
                               <table class="basket-tb">
                                {% for goods in product_list %}
                                   <tr>
                                       <td class="basket-tb-cell-num">{{ forloop.counter }}</td>
                                       <td class="basket-tb-cell-goods">
                                            {% if goods.image_origin %}
                                            <a class="img_fancybox" href="{{ goods.image_origin.url}}" title="{{ goods.name }}">
                                                <img src="{{ goods.image_thumbnail.url}}" alt="" class="basket-img">
                                            </a>
                                            {% else %}
                                            <img src="{{ STATIC_URL }}images/required/noimg.jpg" alt="" class="basket-img">
                                            {% endif %}
                                           <a href="{{ goods.get_absolute_url }}" class="basket-link">{{ goods.name | truncatechars:14 }}</a>
                                       </td>
                                       <td class="basket-tb-cell-amt">
                                           <input type="number" class="field basket-field-amt" name="basket-amt" id="{{goods.id}}" value="{{goods.count}}">
                                       </td>
                                       <td class="basket-tb-cell-price">{{ goods.price }} грн.</td>
                                       <td class="basket-tb-cell-sum">{{ goods.sum }} грн.</td>
                                       <td class="basket-tb-cell-delete">
                                           <span class="icon delete" onclick="return RemoveGoodsBasket.call(this,{{goods.id}})"></span>
                                       </td>
                                   </tr>
                                {% endfor %}
                               </table>
                               <div class="basket-all-sum clearfix">
                                   <div class="basket-all-sum-title left">Итого:</div>
                                   <div class="basket-all-sum-number left">{{ basket_price }} грн.</div>
                               </div>
                               <div class="basket-footer clearfix">
                                   <a href="{% url 'product_list' %}" class="basket-next-link left">Продолжить покупки</a>
                                   {% if product_list %}
                                   <a href="#" class="goods-button button right">Оформить заказ</a>
                                   {% endif %}
                               </div>
                               <form action="#" class="basket-form">
                                   <div class="basket-form-row clearfix">
                                       <label for="delivery" class="left basket-form-label">Способ доставки<span class="required">*</span>:</label>
                                       <select name="delivery" id="delivery" class="field right basket-form-field">
                                        {% for delivery in delivery_list %}
                                        {% if forloop.first %}
                                           <option value="{{delivery.id}}" selected>{{delivery.title}}</option>
                                        {% else %}
                                           <option value="{{delivery.id}}">{{delivery.title}}</option>
                                        {% endif %}
                                        {% endfor %}
                                       </select>
                                   </div>
                                   <div class="basket-form-row clearfix">
                                       <label for="payment" class="left basket-form-label">Способ оплаты<span class="required">*</span>:</label>
                                       <select name="payment" id="payment" class="field right basket-form-field">
                                        {% for payment in payment_list %}
                                        {% if forloop.first %}
                                           <option value="{{ payment.0}}" selected>{{ payment.1 }}</option>
                                        {% else %}
                                           <option value="{{ payment.0 }}">{{ payment.1 }}</option>
                                        {% endif %}
                                        {% endfor %}
                                       </select>
                                   </div>
                                   <div class="basket-form-row clearfix">
                                       <label for="country" class="left basket-form-label">Страна<span class="required">*</span>:</label>
                                       <select name="country" id="country" class="field right basket-form-field">
                                           <option value="Пункт1" selected>Украина</option>
                                       </select>
                                   </div>
                                   <div class="basket-form-row clearfix">
                                       <label for="city" class="left basket-form-label">Город<span class="required">*</span>:</label>
                                     <input type="text" class="field right basket-form-field" id="city" name="city" value="{{user.id|user_city}}">
                                   </div>
                                   <div class="basket-form-row clearfix">
                                       <label for="comment" class="left basket-form-label">Комментарий к заказу</label>
                                       <textarea name="comment" id="comment" class="field right basket-form-field" id="comment"></textarea>
                                   </div>
                                   <div class="small_note">* Просим обратить Ваше внимание минимальная сумма заказа составляет {{price_limit}} грн.</div>
                                   <br>
                                   {% if not user.is_authenticated %}
                                   <div class="small_note">** Для осуществления покупок нужно <a href="{% url 'login' %}">авторизироватся</a></div>
                                   {% else %}
                                   <div class="small_note">** Доставка осуществляется только на контактные данные пользователя. <a href="{% url 'login' %}">Изменить контактные данные</a></div>
                                   {% endif %}
                                   <div class="basket-form-button tar"><button class="button filter-button">Отправить</button></div>
                               </form>
        </div>
        <div class="tab-content tab-content-js">
            <div class="tablebox basket-header">
                <div class="cellbox basket-tb-cell-num">№</div>
                <div class="cellbox basket-tb-cell-goods">Uid</div>
                <div class="cellbox basket-tb-cell-sum">Сумма</div>
                <div class="cellbox basket-tb-cell-delete">Статус</div>
            </div>
            <table class="basket-tb">
                {% for order in order_list %}
                <tr>
                    <td class="basket-tb-cell-num">{{ forloop.counter }}</td>
                    <td class="basket-tb-cell-goods">
                        {{ order.uid }}
                    </td>
                    <td class="basket-tb-cell-sum">{{ order.get_order_price }} грн.</td>
                    <td class="basket-tb-cell-delete">
                        {{ order.get_status_display }}
                    </td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>
    <!--end tabs-->
</section>
{% endblock %}